version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file: .env

  gocrud:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env

volumes:
  mongo-data:
