---
# SPDX-FileCopyrightText: 2020 James Mills / prologic
#
# SPDX-License-Identifier: MIT

name: reviewdog
on: [pull_request]
jobs:
  remark-lint:
    name: runner / remark-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: install remark presets
        run: npm install
        shell: bash
      - name: remark-lint
        uses: reviewdog/action-remark-lint@7c4b1f5f1cf73b426e8b2c1921fb2888d84c55d5 # v5.19.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
