---
# SPDX-FileCopyrightText: 2020 James Mills / prologic
#
# SPDX-License-Identifier: MIT

name: reviewdog
on: [pull_request]
jobs:
  remark-lint:
    name: runner / remark-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: install remark presets
        run: npm install
        shell: bash
      - name: remark-lint
        uses: reviewdog/action-remark-lint@82225f7db5b4a3caaca3052733b6800fa7d109b0 # v5.18.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
